server:
  port: 8090

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/msa_db
    driver-class-name: org.postgresql.Driver
    username: yangyag
    password: yangyag1!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true