services:
  eureka-service:
    image: yangyag2/msa-eureka-service-image:v1.1.0
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - msa-network

  post-service:
    image: yangyag2/msa-post-service-image:v1.1.0
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - msa-network
    depends_on:
      eureka-service:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  reply-service:
    image: yangyag2/msa-reply-service-image:v1.1.0
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - msa-network
    depends_on:
      eureka-service:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  api-gateway:
    image: yangyag2/msa-api-gateway-image:v1.1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - msa-network
    depends_on:
      eureka-service:
        condition: service_healthy
      post-service:
        condition: service_started
      reply-service:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure

networks:
  msa-network:
    driver: bridge