server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/boards/**
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/api/replies/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/