server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<segment>.*), /api/posts/${segment}
        - id: reply-service
          uri: lb://reply-service
          predicates:
            - Path=/api/replies/**
          filters:
            - RewritePath=/api/replies/(?<segment>.*), /api/replies/${segment}
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/categories/**
          filters:
            - RewritePath=/api/categories/(?<segment>.*), /api/categories/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true

# 별도의 CORS 설정 섹션
cors:
  allowed-origins: http://localhost:8083, http://frontend-service:8083