server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<segment>.*), /api/posts/${segment}
        - id: reply-service
          uri: lb://reply-service
          predicates:
            - Path=/api/replies/**
          filters:
            - RewritePath=/api/replies/(?<segment>.*), /api/replies/${segment}
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/categories/**
          filters:
            - RewritePath=/api/categories/(?<segment>.*), /api/categories/${segment}
        - id: keycloak
          uri: lb://keycloak-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8091/realms/msa-realm
          jwk-set-uri: http://keycloak-service:8091/realms/msa-realm/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true

cors:
  allowed-origins: http://localhost:8083, http://frontend-service:8083, http://keycloak-service:8091