server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<segment>.*), /api/posts/${segment}
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/api/replies/**
          filters:
            - RewritePath=/api/replies/(?<segment>.*), /api/replies/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/