server:
  port: 8091

spring:
  main:
    web-application-type: reactive
  application:
    name: keycloak-service
  cloud:
    gateway:
      routes:
        - id: keycloak
          uri: http://keycloak:8090
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

keycloak:
  auth-server-url: http://keycloak:8090/auth